---
title: "Prediction Model on Titanic Competition"
author: 'Anton Aksyonov'
date: '11.04.2017'
output:
  html_document:
    number_sections: true
    toc: true
    fig_width: 9
    fig_height: 5
    theme: yeti
    highlight: textmate
---

# Introducing

# Loading libralies and data

```{r, message=FALSE, warning=FALSE}
# Load libraries 
library(ggplot2)
library(ggrepel)
library(data.table)
library(MASS)
library(ROCR)
library(robust)

```


```{r, message=FALSE, warning=FALSE}
# Load train data
train_data <- fread("~/R/Binary-classification-model-Titanic/dataset/train.csv", stringsAsFactors = TRUE)
train_data$type <- 1
train_data$Survived.f <- as.factor(train_data$Survived)
levels(train_data$Survived.f) <- c("Died", "Survived")

# Load train data
test_data <- fread("~/R/Binary-classification-model-Titanic/dataset/test.csv", stringsAsFactors = TRUE)
test_data$type <- 0
```


```{r, message=FALSE, warning=FALSE}
# We combine training data with test data
full_data <- rbindlist(l = list(train_data,test_data)
                       ,use.names = TRUE
                       ,fill = TRUE
                       ,idcol = NULL)

full_data$Pclass <- as.factor(full_data$Pclass)
levels(full_data$Pclass) <- c("1st Class", "2nd Class", "3rd Class")

```

## New functions
```{r, message=FALSE, warning=FALSE}

# multiplot ####
f.multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}




f.show_na_and_empty <- function(){

  na_values <- data.frame('NA_and_Empty_train' = apply(X = full_data[full_data$type == 1,],2, function(x){sum(is.na(x) | x == "")})
                        ,'NA_and_Empty_test' = apply(X = full_data[full_data$type == 0,],2, function(x){sum(is.na(x) | x == "")}))
  
  na_values <- na_values[na_values$NA_and_Empty_train>0 | na_values$NA_and_Empty_test>0,]

  return(na_values)    
}

```


```{r}
f.show_na_and_empty()
```

# Exploratory visual analysis
```{r, message=FALSE, warning=FALSE,fig.align='center'}
ggplot(full_data[full_data$type == 1] , aes(x = Survived.f, y = type, fill = Survived.f)) + 
  ggtitle("How many of dead and survivors") + 
  labs(x = NULL, y = "Number of Passengers") +
  geom_bar(stat = "identity", alpha = 0.7) + 
  facet_grid(. ~ Pclass)
```


```{r, message=FALSE, warning=FALSE,fig.align='center'}
ggplot(full_data[full_data$type == 1] , aes(x = Age, fill = Survived.f)) + 
  ggtitle("Distribution of survivors and deaths by age. Grid by Class") + 
  labs(x = NULL, y = "Number of Passengers") +
  geom_histogram(bins = 100, alpha = 0.5
                 ,binwidth = 1
                 ,col = 'black') + 
  scale_x_continuous(breaks=seq(0, 90, 10 )) +
  facet_grid(Pclass ~ .)
```

# Names 
```{r, message=FALSE, warning=FALSE}
full_data$Title <- gsub('.*, |\\..*', '', full_data$Name) 
full_data$Title <- as.factor(full_data$Title)
title_tab <- full_data[,list(number_of_distinct_orders = uniqueN(PassengerId)), by = list(Title)]
title_tab[order(-number_of_distinct_orders)]
```


```{r, message=FALSE, warning=FALSE, results = 'hide'}
# add a 'Rare' title
full_data[Title!='Mr' & Title!='Miss' & Title!='Mrs' & Title!='Master',Title:='Rare']
```


```{r, message=FALSE, warning=FALSE}
title_tab <- full_data[,list(number_of_distinct_orders = uniqueN(PassengerId)), by = Title]
title_tab[order(-number_of_distinct_orders)]
```

# Missing Values

## Age
```{r, message=FALSE, warning=FALSE}
f.show_na_and_empty()
```
```{r, message=FALSE, warning=FALSE}

age_predict_model <- lm(Age ~ SibSp + Title + Fare + Pclass + Parch, data = full_data[!is.na(Age)&!is.na(Fare)])

stepAIC(age_predict_model, direction = 'both')

```


```{r, message=FALSE, warning=FALSE, results='hide',fig.align='center'}

age_predict_model <- lm(formula = Age ~ SibSp + Title + Pclass, data = full_data[!is.na(Age) & 
    !is.na(Fare)])

summary(age_predict_model)

full_data[is.na(Age),Age:=round(predict.lm(age_predict_model,full_data[!is.na(Age) & 
    !is.na(Fare)]),0)]


ggplot(data = full_data, aes(x = Age)) + 
  geom_histogram(bins = 100, alpha = 0.5
                 ,binwidth = 1
                 ,col = 'black')


```

## Fare
```{r, message=FALSE, warning=FALSE,fig.align='center'}

ggplot(data = full_data[Pclass == '3rd Class' & Embarked == 'S'], aes(x = Fare)) + 
  geom_histogram(bins = 50, alpha = 0.5
                 ,binwidth = 1
                 ,col = 'black') + 
  geom_vline(aes(xintercept = median(Fare, na.rm = TRUE)),
    colour = 'red', linetype = 'dotdash', lwd = 1)

```

```{r, message=FALSE, warning=FALSE, results='hide'}
full_data[is.na(Fare),list(PassengerId,Pclass,Name,Fare)]
```

```{r, message=FALSE, warning=FALSE, results='hide'}
full_data[is.na(Fare),Fare:=median(full_data[Pclass == '3rd Class' & Embarked == 'S',Fare],na.rm = TRUE)]

full_data[PassengerId == 1044,list(PassengerId,Pclass,Name,Fare)]

```

## Embarked
```{r, message=FALSE, warning=FALSE}

ggplot(data = full_data, aes(x = Embarked, y = type, fill = Embarked)) + 
  geom_bar(stat = "identity", alpha = 0.7)


```

```{r, message=FALSE, warning=FALSE, results='hide'}
full_data[Embarked == "", Embarked:='S']
```


```{r, message=FALSE, warning=FALSE}
f.show_na_and_empty()
```



# New Features

## Cabin Kind
```{r, message=FALSE, warning=FALSE, fig.align='center', results='hide'}

full_data[,Cabin:= as.character(Cabin)]
full_data[,Cabin_number:= sapply(full_data$Cabin,function(x) strsplit(x,'[A-Z]')[[1]][2])]
full_data[,Cabin_number:=as.numeric(Cabin_number)]
full_data[is.na(Cabin_number),Cabin_number:=0]

full_data[Cabin_number==0, Cabin_kind:="0_Unknow"]
full_data[Cabin_number!=0 & Cabin_number < 50,Cabin_kind:="1_Front"]
full_data[Cabin_number!=0 & Cabin_number >= 50 & Cabin_number < 100,Cabin_kind:="2_Middle"]
full_data[Cabin_number!=0 & Cabin_number >= 100,Cabin_kind:="3_End"]

cabin_tab <- full_data[,.(count_person = uniqueN(PassengerId))
                       ,by = list(Cabin_kind, Pclass, Survived.f,type)]
ggplot(data = cabin_tab, aes(x = Cabin_kind, y = count_person, fill = Pclass)) + 
  geom_bar(stat = 'identity', alpha = 0.7)

```

```{r, message=FALSE, warning=FALSE, fig.align='center', results='hide'}
ggplot(data = cabin_tab[type == 1], aes(x = Cabin_kind, y = count_person, fill = Survived.f)) + 
  geom_bar(stat = 'identity', alpha = 0.7) + 
  facet_grid(Pclass ~ .)

```

## Person

```{r, message=FALSE, warning=FALSE, fig.align='center', results='hide'}

full_data[,Person:= as.factor(ifelse(full_data$Age< 18
                                       , ifelse(full_data$Sex == 'male','boy','girl')
                                       , ifelse(full_data$Sex == 'male','man','woman')))]


p1_person <- 
  ggplot(data = full_data[type == 1,], aes(x = Person, y = type, fill = Survived.f)) + 
  geom_bar(stat = 'identity', alpha = 0.7) + 
  facet_grid(Pclass ~ .)

p2_person <- 
  ggplot(data = full_data[type == 1,], aes(x = Person, y = type, fill = Survived.f)) + 
  geom_bar(stat = 'identity',position = "fill", alpha = 0.7) + 
  facet_grid(Pclass ~ .)

f.multiplot(p1_person, p2_person)

```

## Family size
```{r, message=FALSE, warning=FALSE, results='hide'}
full_data[,Family_size:=SibSp+Parch+1]
```

# Prediction model

```{r, message=FALSE, warning=FALSE}
train_data <- full_data[type==1]
test_data <- full_data[type==0]

train_data.p <- train_data[,.(Survived,Pclass,Sex,Age,Fare,SibSp,Parch,Person, Embarked,Cabin_kind,Family_size)]

prediction_model_glm <- glm(Survived ~ . , data = train_data.p, family = 'binomial')

stepAIC(prediction_model_glm, direction = 'backward')

```

```{r, message=FALSE, warning=FALSE}

prediction_model_glm <- glm(Survived ~ Pclass + 
                              Age + 
                              Fare +
                              #Embarked +
                              Cabin_kind + 
                              Family_size +
                              Sex
                            , family = "binomial"
                            , data = train_data.p
                            , method = 'cubif')







train_data$prob <- predict(prediction_model_glm,train_data,type = 'response')


train_data$pred <- ifelse(predict(prediction_model_glm,train_data,type = 'response')>0.6065,1,0)


sum(train_data$Survived == train_data$pred) / 891

summary(prediction_model_glm)

```

## ROCR
```{r}
pred_fit <- prediction(train_data$prob, train_data$Survived)
perf_fit <- performance(pred_fit, "tpr", "fpr")

auc  <- performance(pred_fit, measure = "auc")
auc <- auc@y.values[[1]]

plot(perf_fit, colorize=T , print.cutoffs.at = seq(0,1,by=0.1))
lines(c(0,1),c(0,1))
text(0.6,0.2,paste("AUC = ", round(auc,4), sep=""), cex=1.4)

```

```{r, message=FALSE, warning=FALSE}

test_data[,Survived:=ifelse(predict(prediction_model_glm,test_data,type = 'response')>0.6065,1,0)]
final_solution <- test_data[,1:2]
write.csv(final_solution, file = 'final_solution_new.csv', row.names = FALSE)

```



